### ISSUE TITLE
Update README with tested code releases

### ISSUE THREAD

**Issue by brilong** [netscaler/ansible-collection-netscaleradc#108]
Could you update the main README with the exact code releases you've tested against?  My team is still using 11.1 train of code and we hope to migrate to a 12.1 SSP release in the near future.  Understanding exactly which releases you test against would be very helpful.  Thanks.

**Comment by giorgos-nikolopoulos** [comment]
This will require some work to automate tests against multiple versions.

So far we test with the latest available GA for ADC 13.0.

**Comment by brilong** [comment]
If your audience for these modules is enterprise customers, I would suggest you need to test the various versions that are in use by those customers.  Enterprise customers typically would not be running the latest GA release. If you believe enterprise customers should stick with whatever citrix_adc modules are included in the upstream Ansible release and only bleeding-edge users should be installing modules manually from this Git repo, please let me know.  The whole reason my team is using your modules directly instead of what was in upstream Ansible was because of lack of feature parity.  Thank you.

**Comment by giorgos-nikolopoulos** [comment]
I agree with you.

We are currently working on verifying the modules with Ansible and putting them on Ansible Galaxy as this is the new distribution method for modules from Ansible version 2.9 onwards.

During this work we will try to incorporate as much as we can of the feedback we have received for improving the modules and their documentation.

**Comment by sumanth-lingappa** [comment]
Hello @brilong, I know it's too late reply here.

We recently introduced ansible-integration-tests against two versions of ADC (CPX) using github-actions. Below is the equivalent code.

let me know if you need more details.

https://github.com/netscaler/ansible-collection-netscaleradc/blob/7eee55f1677a75f8eaca085cd3ad498be68791ed/.github/workflows/test.yml#L108

**Comment by sumanth-lingappa** [comment]
closing this as there was no response for 2 weeks. Please re-open if required.
