### ISSUE TITLE
Could find parameter how to link server certificate to Root or Intermediate Certificate

### ISSUE THREAD

**Issue by vahric** [netscaler/ansible-collection-netscaleradc#201]
Hello,
Trying to link my server certificate to installed intermediate certificate on appliance via ansible but couldn't find how ... 

its looks like available in nitro api the https://developer-docs.citrix.com/projects/netscaler-nitro-api/en/12.0/configuration/ssl/sslcertlink/ 

Couldn't see also here add, update or something, only get and count .... 
Could you pls help how can i do it?

**Comment by vahric** [comment]
One more , ansible or terraform , both have support same level integration and features ? Citrix advise use terraform instead of Ansible ? Which one is ahead ?

**Comment by vadharm** [comment]
Currently ADC terraform modules could be more than Ansible, but ADC Ansible modules has a generic resoruce that can be used to configure multiple endpoints. We aim to have parity for both integrations.

**Comment by vahric** [comment]
Hello Mayur Vadhar , i saw that, with less coding i did everything with terraform. For example i linked CA Cert and Server Cert with it.

**Comment by shriraja22** [comment]
@vahric . Pretty old thread but this is how am using ansible to link SSL certs

     - name: Link SSL Key
       delegate_to: localhost
       ignore_errors: true
       netscaler_nitro_request:
         nsip: "{{ nsip }}"
         nitro_user: "{{ nitro_user }}"
         nitro_pass: "{{ nitro_pass }}"
         nitro_protocol: https
         validate_certs: no
         operation: action
         action: link
         resource: sslcertkey
         attributes:
           certkey: 'abc.com'
           linkcertkeyname: 'test'

**Comment by sumanth-lingappa** [comment]
Thank you @shriraja22. 
Closing this issue for now.
@vahric, please checkout our new [`netscaler.adc`](https://github.com/netscaler/ansible-collection-netscaleradc) collection
