### ISSUE TITLE
[BUG] servicegroup_exists() 'NoneType' object is not callable

### ISSUE THREAD

**Issue by brentisaacs** [netscaler/ansible-collection-netscaleradc#236]
**Describe the bug**
ansible-playbook [core 2.13.4]
python version = 3.9.12 (main, Jul 27 2022, 19:05:33) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]

Updates to the backend of ansible is causing the request (r) to return as an Exception for new service groups.  

TASK [Set service group and associate to backend on Citrix ADC] ****************
task path: adc_vserver_add.yml:20
failed: [Sample] (item=myadc.local) => {"ansible_loop_var": "item", "changed": false, "item": "myadc.local", "loglines": ["ModuleExecutor.calculate_configured_servicegroup()", "calculated configured servicegroup {'comment': 'Created or updated by Ansible for Brent Isaacs', 'servicetype': 'HTTP', 'monthreshold': '1', 'usip': 'NO', 'servicegroupname': 'brent-test-http', 'cipheader': 'x-forwarded-for', 'cip': 'ENABLED'}", "ModuleExecutor.calculate_configured_servicemembers()", "calculated configured service members [{'servername': 'brent-test', 'servicegroupname': 'brent-test-http', 'port': 80}]", "ModuleExecutor.calculate_configured_monitor_bindings()", "calculated configured monitor bindings [{'servicegroupname': 'brent-test-http', 'monitor_name': 'tcp'}]", "ModuleExecutor.update_or_create()", "ModuleExecutor.servicegroup_exists()"], "msg": "Exception : 'NoneType' object is not callable"

This can be easily remedied _with_ backward compatibility to Ansible 2.9.27 on Python 2.7 by updating the replacing the following string in citrix/adc/plugins/module_utils/citrix_adc.py

Original string:

if r is not None:

Forward-compatible string:

if r is not None and not isinstance(r, Exception):

**Comment by brentisaacs** [comment]
I would make a branch and PR, but this repo isn't open for public contribution

**Comment by sumanth-lingappa** [comment]
Hello @brentisaacs , we are working on policy changes to accept public contributions. 

You can still go ahead and create a PR which resolves this. This will definitely help the community.

**Comment by brentisaacs** [comment]
Thank you, @sumanth-lingappa.  I have created the following pull request: https://github.com/citrix/citrix-adc-ansible-modules/pull/249

**Comment by brentisaacs** [comment]
Oh...I get it.  This repository is more or less abandoned, huh?

**Comment by sumanth-lingappa** [comment]
No @brentisaacs, not at all.
This repo is very much active.

However, we are working on a new version of `netscaler.adc` ansible collection.
We have recently released a `alpha` version of our new ansible collection.
You can find more details below:
https://github.com/citrix/citrix-adc-ansible-modules/tree/v2.0.0-alpha

We have intention to replace `netscaler.adc` ansible collection in the place of `citrix.adc` in few months.

Request you to start using our new `netscaler.adc` and provide us your feedback. We will accommodate your suggestions in our new `netscaler.adc` ansible collection.

**Comment by sumanth-lingappa** [comment]
@brentisaacs, please check the new [`netscaler.adc`](https://github.com/netscaler/ansible-collection-netscaleradc)  collection. This should resolve ansible version issue.

Also, write to us at NetScaler-AutomationToolkit@cloud.com how you are using our `citrix.adc` OR `netscaler.adc` ansible collections. This helps us to streamline our priorities in this collection
