### ISSUE TITLE
[BUG] citrix_adc_service_module documentation for monitor_bindings

### ISSUE THREAD

**Issue by pkodzis** [netscaler/ansible-collection-netscaleradc#243]
**Describe the bug**
citrix_adc_service_module documentation for monitor_bindings says monitor_bindings is expecting the "list"
while in the code of the module citrix_adc_service_module.py it reasy expects dict:

            'monitor_bindings': {
                'attributes_list': [
                    'monitor_name',
                    'monstate',
                    'weight',
                    'passive',
                ],
                'transforms': {
                    'monstate': lambda v: v.upper(),
                    'weight': str,
                },
                'get_id_attributes': [
                    'name',
                ],
                'delete_id_attributes': [
                    'monitor_name',
                    'name',
                ]

**To Reproduce**
see exisging citrix_adc_service_module doc for monitor_bindings and compare with citrix_adc_service_module.py source code.

**Comment by sumanth-lingappa** [comment]
@pkodzis, if you are able to get this done with `netscaler.adc` collection, can I request you to close this issue?

**Comment by pkodzis** [comment]
ack - solved in 2.1.0 - thank you so much! :)
