### ISSUE TITLE
[BUG] citrix_adc_server fails to work with nitro_auth_token

### ISSUE THREAD

**Issue by pkodzis** [netscaler/ansible-collection-netscaleradc#247]
**Describe the bug**
citrix_adc_server fails to work with nitro_auth_token - it enforces using nitro_user and nitro_pass. That makes impossible to create servers on other partitions but the default one.

**To Reproduce**
Steps to reproduce the behaviour:
1. My ansible-playbook is...
     - name: setup server
      delegate_to: localhost
      citrix_adc_server:
        nsip: "{{provider.nsip}}"
        nitro_auth_token: "{{nitro_auth_token}}"
        validate_certs: no
        state: present
        name: server-1
        ipaddress: 192.168.10.123

3. The command I executed is...
ansible-playbook -vvvvv 1.yml

5. The ansible-playbook logs are...
7. I am seeing the below error...
fatal: [REMOVED -> localhost]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "api_path": null,
            "bearer_token": null,
            "comment": "vars",
            "delay": null,
            "disabled": false,
            "domain": null,
            "domainresolveretry": null,
            "graceful": null,
            "instance_id": null,
            "instance_ip": null,
            "instance_name": null,
            "ipaddress": "192.168.10.123",
            "ipv6address": false,
            "is_cloud": false,
            "mas_proxy_call": false,
            "name": "server-1",
            "nitro_auth_token": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "nitro_pass": null,
            "nitro_protocol": "https",
            "nitro_timeout": 310.0,
            "nitro_user": null,
            "nsip": "REMOVED",
            "save_config": true,
            "state": "present",
            "td": null,
            "translationip": null,
            "translationmask": null,
            "validate_certs": false
        }
    },
    "msg": "You must provide a valid nitro user name"
}

**Expected behaviour**

I need thre module to be able to work with nitro_auth_token rather than user/pass authneticaiton, so I could in advance switch to the partitition that I need to work on and continue my session on that partition.

**Environment (please complete the following information):**
 - Python version `python --version` output
 - Ansible version `ansible --version` output

$ python3 --version
Python 3.8.10
$ ansible --version
ansible [core 2.12.10]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/pkodzis/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.8/dist-packages/ansible
  ansible collection location = /home/pkodzis/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.8.10 (default, Jun 22 2022, 20:18:18) [GCC 9.4.0]
  jinja version = 2.10.1
  libyaml = True

**Comment by sumanth-lingappa** [comment]
@pkodzis, if you are able to get this done with `netscaler.adc` collection, can I request you to close this issue?

**Comment by pkodzis** [comment]
ack - solved in 2.1.0 - thank you so much! :)
