### ISSUE TITLE
[BUG] citrix_adc_servicegroup fails create with Autoscale DNS

### ISSUE THREAD

**Issue by pkodzis** [netscaler/ansible-collection-netscaleradc#251]
**Describe the bug**

ansible fails on adding servicegroup with Autoscale DNS:

result of post {'http_response_data': {'url': 'https://10.147.254.35/nitro/v1/config/servicegroup?action=enable', 'status': 599, 'date': 'Fri, 13 Jan 2023 10:06:28 GMT', 'server': 'Apache', 'x-frame-options': 'SAMEORIGIN', 'expires': 'Thu, 19 Nov 1981 08:52:00 GMT', 'cache-control': 'no-store, no-cache, must-revalidate, post-check=0, pre-check=0', 'pragma': 'no-cache', 'feature-policy': \"camera 'none'; microphone 'none'; geolocation 'none'\", 'referrer-policy': 'no-referrer', 'x-xss-protection': '1; mode=block', 'x-content-type-options': 'nosniff', 'content-length': '184', 'content-type': 'application/json; charset=utf-8', 'connection': 'close', 'msg': 'HTTP Error 599: Netscaler specific error'}, 'nitro_errorcode': 257, 'nitro_message': 'Operation not permitted [Enabling / Disabling is not permitted as it has auto scale members. Try unbinding auto scale members.]', 'nitro_severity': 'ERROR', 'data': {'errorcode': 257, 'message': 'Operation not permitted [Enabling / Disabling is not permitted as it has auto scale members. Try unbinding auto scale members

After commenting this code in citrix_adc_servicegroup.py, it lets create all as expected. it seems like this part should not be called when building new servicegroup:

        #log('disable/enable post data %s' % post_data)
        #result = self.fetcher.post(post_data=post_data, resource='servicegroup', action=action)
        #log('result of post %s' % result)

        #if result['http_response_data']['status'] != 200:
        #    msg = 'Disable/Enable operation failed'
        #    self.module.fail_json(msg=msg, **self.module_result)

**Environment (please complete the following information):**
$ python3 --version
Python 3.8.10
$ ansible --version
ansible [core 2.12.10]
  config file = None
  ansible python module location = /usr/local/lib/python3.8/dist-packages/ansible
  ansible collection location = /home/pkodzis/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.8.10 (default, Nov 14 2022, 12:59:47) [GCC 9.4.0]
  jinja version = 2.10.1
  libyaml = True

Nitro SDK installed from copy donwloaded fron NetScaler running:
:Primary> sh ver
        NetScaler NS13.0: Build 85.15.nc, Date: Mar 10 2022, 07:24:58   (64-bit)

**Comment by pkodzis** [comment]
To narrow down, for me the error appears when creating "autoscale: DNS" servicegroup with members that are FQDN based.
If create "autoscale: DNS" servicegroup with members that are IP based, disable/enable passes.
Disable/enable also passes when "autoscale: DNS" servicegroup members are mix of FQDN and IP based.

**Comment by sumanth-lingappa** [comment]
@pkodzis, if you are able to get this done with `netscaler.adc` collection, can I request you to close this issue?

**Comment by pkodzis** [comment]
ack - this works as expected in 2.1.0 - thank you so much! :)
