### ISSUE TITLE
[QUESTION] How to deal with HA-Pair

### ISSUE THREAD

**Issue by pbptaker** [netscaler/ansible-collection-netscaleradc#252]
Dear Community

How to deal with an HA-Pair? I can connect to the primary node using the NSIP, but I can't connect the management enabled SNIP.
I can connect to the secodary NSIP of course.
On the SNIP I'm getting an TLS error. I wonder why the TLS settings are applied using an SSL Profile. So both SNIP and NSIP should use the same TLS Settings imo.

Maybe connect to both and find out which is the primary?

Thank you

Pbptaker

**Comment by sumanth-lingappa** [comment]
@pbptaker, I am able to configure the primary using the SNIP with mgmtaccess.

Please share more details on your error.

BTW, I used the new `netscaler.adc` ansible collection. I recommend you to use the same and not the `citrix.adc` ansible collection.

I will keep this open for few more days to hear from you.

**Comment by pbptaker** [comment]
Thank you sumanth-lingappa
We are currently trying to do the migrato to the citrix-ingress controller https://github.com/netscaler/netscaler-k8s-ingress-controller. Thus not clear if we continue using ansible. For ansible we have to upgrade our ansible images since there is a new version of the collections since november 2023 (even available in ansible-galaxy if i'm not wrong)
