### ISSUE TITLE
[BUG] Ansible Module not Backward compatible to Netscaler Version NS11.1: Build 59.158.n

### ISSUE THREAD

**Issue by shriraja22** [netscaler/ansible-collection-netscaleradc#265]
**Describe the bug**
1. The old version does not accept priority  When I pass this I get the below error

"nitro exception errorcode=693, message=Advanced expressions based  policies cannot be bound to a classic CS vserver., severity=ERROR"}

2. The new version mandates a priority field. If I do pass a priority field I get below error. 

"msg": "nitro exception errorcode=695, message=Priority is mandatory for advanced expressions., severity=ERROR"}

**To Reproduce**
Here is a sample Playbook

    - name: Bind CS Policy 
      delegate_to: localhost
      ignore_errors: true
      citrix_adc_nitro_resource:
        nsip: "{{ nsip }}"
        nitro_user: "{{ nitro_user }}"
        nitro_pass: "{{ nitro_pass }}"
        nitro_protocol: http
        validate_certs: no
        state: present
        workflow: "{{ workflow.csvserver_cspolicy_binding }}"

        resource:
          name: 'Test:443'
          targetlbvserver: 'cs.vs.test-vip'
          policyname: "cs.test"
          bindpoint: REQUEST
          priority: 10

Workflow:
  csvserver_cspolicy_binding:
    lifecycle: binding
    endpoint: csvserver_cspolicy_binding
    bound_resource_missing_errorcode: 258
    primary_id_attribute: name
    delete_id_attributes:
      - policyname
      - bindpoint
      - priority
    allow_recreate: true

**Expected behaviour**
Would expect the Nitro API to be backwards compatible and allow to bind cs policy to target lbvserver 

**Screenshots**

**Environment (please complete the following information):**
 (venv) shri@srajagopalan ansible-netscaler % ansible --version
ansible [core 2.11.12] 
  config file = None
  configured module search path = ['/Users/shri/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/shri/Documents/python_venv/venv/lib/python3.10/site-packages/ansible
  ansible collection location = /Users/shri/.ansible/collections:/usr/share/ansible/collections
  executable location = /Users/shri/Documents/python_venv/venv/bin/ansible
  python version = 3.10.12 (main, Jun  7 2023, 00:37:42) [Clang 14.0.0 (clang-1400.0.29.202)]
  jinja version = 3.1.2
  libyaml = True

**Comment by sumanth-lingappa** [comment]
@shriraja22,
Can you please post the `show run` lines related to this binding? i.e., target lb vserver, cs vserver, cs policy etc ?

**Comment by shriraja22** [comment]
Hi @sumanth-lingappa . Please see the requested configs. I have posted a Sample for reference but I have a lot of policies

add cs vserver Test:443 SSL 10.10.10.10 443 -cltTimeout 180 -tcpProfileName nstcp_default_WAN_profile

add cs policy cs.test -url "/TEST/205/service/*"

add lb vserver cs.vs.test-vip HTTP 0.0.0.0 0 -persistenceType NONE -timeout 30 -cltTimeout 9000

bind cs vserver Test:443 -policyName cs.ITJXdcs205 -targetLBVserver vs.ITJXBLOB-VIP

**Comment by sumanth-lingappa** [comment]
@shriraja22, can you please help me with the `show run` of `cs.ITJXdcs205` policy?

**Comment by shriraja22** [comment]
@sumanth-lingappa . Please check here. I have update my comment . If possible please help update that

add cs policy cs.TEST205 -url "/TEST/205/service/*"

**Comment by sumanth-lingappa** [comment]
@shriraja22, can you update this issue with your findings?

**Comment by sumanth-lingappa** [comment]
closing this as there was no response for 2 weeks. Please re-open if required.
