### ISSUE TITLE
[BUG] v2.0.0. ALPHA: vpnvserver ERROR for authentication value when set to "True"

### ISSUE THREAD

**Issue by krausi24** [netscaler/ansible-collection-netscaleradc#274]
**Describe the bug**
Setting the value of authentication to "True" in vpnvserver module result in ERROR:
"msg": "ERROR: create_resource FAILED; status_code: 400; Reason:{'errorcode': 1097, 'message': 'Invalid argument value [true]', 'severity': 'ERROR'}"

- name: create gateway
  tags: vpnvserver
  delegate_to: localhost
  netscaler.adc.vpnvserver:
    nsip: "{{ ansible_host }}"
    nitro_user: "{{ nitro_user }}"
    nitro_pass: "{{ nitro_pass }}"
    validate_certs: "{{ validate_certs }}"
    state: "present"

    name: "{{ NGVS_name }}"
    servicetype: "{{ NGVS_servicetype }}"
    ipv46: "{{ NGVS_ipv46 }}" 
    port: "{{ NGVS_port }}"
    icaonly: "{{ NGVS_icaonly }}"
    authentication: "{{ NGVS_authentication }}"
    authnprofile: "{{ NGVS_authnprofile }}".

Variables:
NGVS_authentication: True

**Expected behaviour**
API call is made with value True

**Screenshots**
![image](https://github.com/citrix/citrix-adc-ansible-modules/assets/128399931/f14b42f6-973e-44fe-b964-16937635a8e8)
**Environment (please complete the following information):**
ansible [core 2.14.6]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/dkr/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  ansible collection location = /home/dkr/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.10.6 (main, Mar 10 2023, 10:55:28) [GCC 11.3.0] (/usr/bin/python3)
  jinja version = 3.0.3
  libyaml = True

**Additional context**
Setting the value for authentication to 123 as an example the ERROR is: 
fatal: [dkr_adc8 -> localhost]: FAILED! => {"changed": false, "msg": "value of authentication must be one of: True, False, got: 123"}

**Comment by sumanth-lingappa** [comment]
Thank you for raising this ticket @krausi24.

This is fixed in the latest release. Please re-install the `netscaler.adc` collection

The possible values for `authentication` attribute is either `ON` or `OFF`

![image](https://github.com/netscaler/ansible-collection-netscaleradc/assets/42572246/a809cec3-e947-4f4e-b221-b6c3f6264391)

You can find the documentation for this module below:
- https://netscaler.github.io/ansible-collection-netscaleradc/collections/netscaler/adc/vpnvserver_module.html


> Since ON and OFF are termed as booleans by YAML parser, it is recommended to enclose these in quotes as stated below

Please re-open this issue if this issue still persists at your end.

**Comment by krausi24** [comment]
HI Sumanth,

thanks and kind regards.


DANIEL KRAUSE
Solution Expert | Consulting
mobile +49 151 11353902
mail ***@***.***
web http://www.braincon.de/
braincon GmbH
Lise-Meitner-Straße 1-13
42119 
Wuppertal

Sitz der Gesellschaft: Alte Bahnhofstraße 54, 64380 Roßdorf, Geschäftsführer: Andreas Huther, Sascha Zimmer, Amtsgericht Darmstadt: HRB88834, USt.-ID: DE270472736
Diese E-Mail und eventuelle Anhänge sind allein für den bezeichneten Adressaten bestimmt. Sie können vertrauliche Informationen enthalten, so dass jede Form der Kenntnisnahme, Veröffentlichung, Vervielfältigung und Weitergabe des Inhalts dieser E-Mail unzulässig ist. Wenn Sie diese E-Mail irrtümlich erhalten haben, informieren Sie bitte unverzüglich den Absender per E-Mail und löschen diese E-Mail von Ihrem Computer, ohne Kopien anzufertigen. Vielen Dank.

Von: Sumanth Lingappa ***@***.***>
Gesendet: Montag, 25. September 2023 10:30
An: netscaler/ansible-collection-netscaleradc ***@***.***>
Cc: Daniel Krause ***@***.***>; Mention ***@***.***>
Betreff: Re: [netscaler/ansible-collection-netscaleradc] [BUG] v2.0.0. ALPHA: vpnvserver ERROR for authentication value when set to "True" (Issue #274)


Achtung, E-Mail kommt von extern!

Sie erhalten nicht oft eine E-Mail von ***@***.******@***.***>. Erfahren Sie, warum dies wichtig ist<https://aka.ms/LearnAboutSenderIdentification>


Thank you for raising this ticket @krausi24<https://github.com/krausi24>.

This is fixed in the latest release. Please re-install the netscaler.adc collection

The possible values for authentication attribute is either ON or OFF

[image]<https://user-images.githubusercontent.com/42572246/270277829-a809cec3-e947-4f4e-b221-b6c3f6264391.png>

You can find the documentation for this module below:

  *   https://netscaler.github.io/ansible-collection-netscaleradc/collections/netscaler/adc/vpnvserver_module.html<https://netscaler.github.io/ansible-collection-netscaleradc/collections/netscaler/adc/vpnvserver_module.html>

Since ON and OFF are termed as booleans by YAML parser, it is recommended to enclose these in quotes as stated below

Please re-open this issue if this issue still persists at your end.
