### ISSUE TITLE
[BUG] Module netscaler.adc.servicegroup_lbmonitor_binding fails if monitor is already bound causing playbook termination

### ISSUE THREAD

**Issue by QTjstahl** [netscaler/ansible-collection-netscaleradc#287]
**Describe the bug**
Running netscaler.adc.servicegroup_lbmonitor_binding to bind a specific monitor to an existing service group will fail and cause playbook termination if the specified service group already has the specific monitor bound to it.  It should continue execution, but instead the module terminates and fails the execution.

**To Reproduce**
Steps to reproduce the behaviour:
1. My ansible-playbook is...
```yaml
  - name: Bind TFTP Monitor to Service group
    delegate_to: localhost
    netscaler.adc.servicegroup_lbmonitor_binding:
      nitro_user: "{{ nitro_user }}"
      nitro_pass: "{{ nitro_pass }}"
      nsip: "{{ nsip }}"
      validate_certs: no
      state: present
      monitor_name: vSphereAutoDeploy_TFTP_Monitor
      monstate: "ENABLED"
      port: 69
      servicegroupname: "{{ tftp_servicegroup }}"
```

2. The ansible-playbook command I executed is...
```bash
ansible-playbook netscaler.yml
```

3. The ansible-playbook logs are...
```bash
TASK [Bind TFTP Monitor to Service group] ********************************************************************************
fatal: [XXX.XXX.XXX.XXX -> localhost]: FAILED! => {"changed": true, "loglines": ["DEBUG: Initializing ModuleExecutor for resource servicegroup_lbmonitor_binding", "TRACE: ENTRY: get_valid_desired_states() called with ('servicegroup_lbmonitor_binding',), {}", "TRACE: EXIT: get_valid_desired_states() returned {'absent', 'present'}", "TRACE: ENTRY: get_netscaler_version() called with (<ansible_collections.netscaler.adc.plugins.module_utils.client.NitroAPIClient object at 0x7f2ca1341e40>,), {}", "TRACE: ENTRY: get_resource() called with (<ansible_collections.netscaler.adc.plugins.module_utils.client.NitroAPIClient object at 0x7f2ca1341e40>, 'nsversion'), {}", "TRACE: ENTRY: send() called with (<ansible_collections.netscaler.adc.plugins.module_utils.client.NitroAPIClient object at 0x7f2ca1341e40>, 'GET', 'https://XXX.XXX.XXX.XXX/nitro/v1/config/nsversion'), {}", "DEBUG: self={'_module': <ansible.module_utils.basic.AnsibleModule object at 0x7f2ca1a71330>, 'check_mode': False, 'api_path': 'nitro/v1/config', '_headers': {'Content-Type': 'application/json', 'User-Agent': 'ansible-ctxadc', 'X-NITRO-USER': '********', 'X-NITRO-PASS': '********'}}", "DEBUG: fetch_url()-resonse-info={'url': 'https://XXX.XXX.XXX.XXX/nitro/v1/config/nsversion', 'status': 200, 'date': 'Fri, 29 Sep 2023 16:02:37 GMT', 'server': 'Apache', 'x-frame-options': 'SAMEORIGIN', 'expires': 'Thu, 19 Nov 1981 08:52:00 GMT', 'cache-control': 'no-store, no-cache, must-revalidate, post-check=0, pre-check=0', 'pragma': 'no-cache', 'vary': 'Accept-Encoding', 'feature-policy': \"camera 'none'; microphone 'none'; geolocation 'none'\", 'referrer-policy': 'no-referrer', 'x-xss-protection': '1; mode=block', 'x-content-type-options': 'nosniff', 'content-length': '201', 'content-type': 'application/json; charset=utf-8', 'connection': 'close', 'cookies_string': '', 'cookies': {}, 'msg': 'OK (201 bytes)'}", "TRACE: EXIT: send() returned (200, {'errorcode': 0, 'message': 'Done', 'severity': 'NONE', 'nsversion': {'installedversion': False, 'version': 'NetScaler NS13.1: Build 37.38.nc, Date: Nov 23 2022, 04:42:36   (64-bit)', 'mode': '1'}})", "TRACE: EXIT: get_resource() returned [{'installedversion': False, 'version': 'NetScaler NS13.1: Build 37.38.nc, Date: Nov 23 2022, 04:42:36   (64-bit)', 'mode': '1'}]", "TRACE: EXIT: get_netscaler_version() returned (13.1, 37.38)", "INFO: NetScaler version: 13.1-37.38", "DEBUG: All params (including non module-specific params) are: {'nitro_user': '********', 'nitro_pass': '********', 'nsip': '10.241.99.70', 'validate_certs': False, 'state': 'present', 'monitor_name': 'vSphereAutoDeploy_TFTP_Monitor', 'monstate': 'ENABLED', 'port': 69, 'servicegroupname': 'myservicegroup_tftp_69', 'nitro_protocol': 'https', 'save_config': False, 'api_path': 'nitro/v1/config', 'nitro_auth_token': None, 'customserverid': None, 'dbsttl': None, 'hashid': None, 'nameserver': None, 'order': None, 'passive': None, 'serverid': None, 'weight': None}", "TRACE: ENTRY: _filter_resource_module_params() called with (<ansible_collections.netscaler.adc.plugins.module_utils.module_executor.ModuleExecutor object at 0x7f2ca1a71660>,), {}", "DEBUG: Desired `servicegroup_lbmonitor_binding` module specific params are: {'monitor_name': 'vSphereAutoDeploy_TFTP_Monitor', 'monstate': 'ENABLED', 'port': 69, 'servicegroupname': 'myservicegroup_tftp_69'}", "TRACE: EXIT: _filter_resource_module_params() returned None", "TRACE: ENTRY: get_existing_resource() called with (<ansible_collections.netscaler.adc.plugins.module_utils.module_executor.ModuleExecutor object at 0x7f2ca1a71660>,), {}", "TRACE: ENTRY: get_resource() called with (<ansible_collections.netscaler.adc.plugins.module_utils.client.NitroAPIClient object at 0x7f2ca1341e40>,), {'resource_name': 'servicegroup_lbmonitor_binding', 'resource_id': 'myservicegroup_tftp_69', 'args': {}, 'filter': {'monitor_name': 'vSphereAutoDeploy_TFTP_Monitor', 'port': 69}}", "TRACE: ENTRY: send() called with (<ansible_collections.netscaler.adc.plugins.module_utils.client.NitroAPIClient object at 0x7f2ca1341e40>, 'GET', 'https://XXX.XXX.XXX.XXX/nitro/v1/config/servicegroup_lbmonitor_binding/myservicegroup_tftp_69?filter=monitor_name:vSphereAutoDeploy_TFTP_Monitor,port:69'), {}", "DEBUG: self={'_module': <ansible.module_utils.basic.AnsibleModule object at 0x7f2ca1a71330>, 'check_mode': False, 'api_path': 'nitro/v1/config', '_headers': {'Content-Type': 'application/json', 'User-Agent': 'ansible-ctxadc', 'X-NITRO-USER': '********', 'X-NITRO-PASS': '********'}}", "DEBUG: fetch_url()-resonse-info={'url': 'https://XXX.XXX.XXX.XXX/nitro/v1/config/servicegroup_lbmonitor_binding/myservicegroup_tftp_69?filter=monitor_name:vSphereAutoDeploy_TFTP_Monitor,port:69', 'status': 200, 'date': 'Fri, 29 Sep 2023 16:02:37 GMT', 'server': 'Apache', 'x-frame-options': 'SAMEORIGIN', 'expires': 'Thu, 19 Nov 1981 08:52:00 GMT', 'cache-control': 'no-store, no-cache, must-revalidate, post-check=0, pre-check=0', 'pragma': 'no-cache', 'vary': 'Accept-Encoding', 'feature-policy': \"camera 'none'; microphone 'none'; geolocation 'none'\", 'referrer-policy': 'no-referrer', 'x-xss-protection': '1; mode=block', 'x-content-type-options': 'nosniff', 'content-length': '57', 'content-type': 'application/json; charset=utf-8', 'connection': 'close', 'cookies_string': '', 'cookies': {}, 'msg': 'OK (57 bytes)'}", "TRACE: EXIT: send() returned (200, {'errorcode': 0, 'message': 'Done', 'severity': 'NONE'})", "TRACE: EXIT: get_resource() returned []", "TRACE: EXIT: get_existing_resource() returned {}", "TRACE: ENTRY: main() called with (<ansible_collections.netscaler.adc.plugins.module_utils.module_executor.ModuleExecutor object at 0x7f2ca1a71660>,), {}", "TRACE: ENTRY: create_or_update() called with (<ansible_collections.netscaler.adc.plugins.module_utils.module_executor.ModuleExecutor object at 0x7f2ca1a71660>,), {}", "TRACE: ENTRY: update_diff_list() called with (<ansible_collections.netscaler.adc.plugins.module_utils.module_executor.ModuleExecutor object at 0x7f2ca1a71660>,), {'existing': {}, 'desired': {'monitor_name': 'vSphereAutoDeploy_TFTP_Monitor', 'monstate': 'ENABLED', 'port': 69, 'servicegroupname': 'myservicegroup_tftp_69'}}", "TRACE: EXIT: update_diff_list() returned None", "INFO: Resource servicegroup_lbmonitor_binding:myservicegroup_tftp_69 does not exist. Will be CREATED.", "TRACE: ENTRY: create_resource() called with (<ansible_collections.netscaler.adc.plugins.module_utils.client.NitroAPIClient object at 0x7f2ca1341e40>, 'servicegroup_lbmonitor_binding', {'monitor_name': 'vSphereAutoDeploy_TFTP_Monitor', 'monstate': 'ENABLED', 'port': 69, 'servicegroupname': 'myservicegroup_tftp_69'}), {}", "TRACE: ENTRY: _check_create_resource_params() called with ('servicegroup_lbmonitor_binding', {'monitor_name': 'vSphereAutoDeploy_TFTP_Monitor', 'monstate': 'ENABLED', 'port': 69, 'servicegroupname': 'myservicegroup_tftp_69'}), {}", "TRACE: EXIT: _check_create_resource_params() returned (True, None, {'monitor_name': 'vSphereAutoDeploy_TFTP_Monitor', 'monstate': 'ENABLED', 'port': 69, 'servicegroupname': 'myservicegroup_tftp_69'})", "TRACE: ENTRY: send() called with (<ansible_collections.netscaler.adc.plugins.module_utils.client.NitroAPIClient object at 0x7f2ca1341e40>, 'POST', 'https://XXX.XXX.XXX.XXX/nitro/v1/config/servicegroup_lbmonitor_binding', '{\"servicegroup_lbmonitor_binding\": {\"monitor_name\": \"vSphereAutoDeploy_TFTP_Monitor\", \"monstate\": \"ENABLED\", \"port\": 69, \"servicegroupname\": \"myservicegroup_tftp_69\"}}'), {}", "DEBUG: self={'_module': <ansible.module_utils.basic.AnsibleModule object at 0x7f2ca1a71330>, 'check_mode': False, 'api_path': 'nitro/v1/config', '_headers': {'Content-Type': 'application/json', 'User-Agent': 'ansible-ctxadc', 'X-NITRO-USER': '********', 'X-NITRO-PASS': '********'}}", "DEBUG: fetch_url()-resonse-info={'url': 'https://XXX.XXX.XXX.XXX/nitro/v1/config/servicegroup_lbmonitor_binding', 'status': 409, 'date': 'Fri, 29 Sep 2023 16:02:37 GMT', 'server': 'Apache', 'x-frame-options': 'SAMEORIGIN', 'expires': 'Thu, 19 Nov 1981 08:52:00 GMT', 'cache-control': 'no-store, no-cache, must-revalidate, post-check=0, pre-check=0', 'pragma': 'no-cache', 'feature-policy': \"camera 'none'; microphone 'none'; geolocation 'none'\", 'referrer-policy': 'no-referrer', 'x-xss-protection': '1; mode=block', 'x-content-type-options': 'nosniff', 'content-length': '100', 'content-type': 'application/json; charset=utf-8', 'connection': 'close', 'msg': 'HTTP Error 409: Conflict', 'body': b'{ \"errorcode\": 2133, \"message\": \"The monitor is already bound to the service\", \"severity\": \"ERROR\" }'}", "TRACE: EXIT: send() returned (409, {'errorcode': 2133, 'message': 'The monitor is already bound to the service', 'severity': 'ERROR'})", "TRACE: ENTRY: return_response() called with (), {'status_code': 409, 'response_body': {'errorcode': 2133, 'message': 'The monitor is already bound to the service', 'severity': 'ERROR'}, 'operation': 'create_resource', 'resource_name': 'servicegroup_lbmonitor_binding'}", "ERROR: create_resource FAILED; status_code: 409; Reason:{'errorcode': 2133, 'message': 'The monitor is already bound to the service', 'severity': 'ERROR'}", "TRACE: EXIT: return_response() returned (False, \"ERROR: create_resource FAILED; status_code: 409; Reason:{'errorcode': 2133, 'message': 'The monitor is already bound to the service', 'severity': 'ERROR'}\")", "TRACE: EXIT: create_resource() returned (False, \"ERROR: create_resource FAILED; status_code: 409; Reason:{'errorcode': 2133, 'message': 'The monitor is already bound to the service', 'severity': 'ERROR'}\")", "TRACE: ENTRY: return_failure() called with (<ansible_collections.netscaler.adc.plugins.module_utils.module_executor.ModuleExecutor object at 0x7f2ca1a71660>, \"ERROR: create_resource FAILED; status_code: 409; Reason:{'errorcode': 2133, 'message': 'The monitor is already bound to the service', 'severity': 'ERROR'}\"), {}"], "msg": "ERROR: create_resource FAILED; status_code: 409; Reason:{'errorcode': 2133, 'message': 'The monitor is already bound to the service', 'severity': 'ERROR'}"}
```

4. I am seeing the below error...
```bash
ERROR: create_resource FAILED; status_code: 409; Reason:{'errorcode': 2133, 'message': 'The monitor is already bound to the service', 'severity': 'ERROR'}
```

**Expected behaviour**
Even though it is already bound, I expect the execution to simply note no change is needed and proceed in executing the rest of the playbook.  Not cause a fatal error that terminates execution.

**Environment (please complete the following information):**
 - Python version `python --version` output
 - Python 3.10.12
 - Ansible version `ansible --version` output
 - ansible 2.10.17
  config file = /home/USER/vsphere_auto_deploy/ansible.cfg
  configured module search path = ['/home/USER/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/USER/.local/lib/python3.10/site-packages/ansible
  executable location = /home/USER/.local/bin/ansible
  python version = 3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0]
 - NetScaler version `show ns version` output
NetScaler NS13.1: Build 37.38.nc, Date: Nov 23 2022, 04:42:36   (64-bit)

**Additional context**

**Comment by sumanth-lingappa** [comment]
@QTjstahl, thank you for the BUG file.

I was not able to reproduce the exact error.

Can you please?

1. Provide the complete standalone ansible-playbook (which has adding servicegroup, adding lbmonitor and the binding)? It will help to reproduce the issue and update you sooner.
2. Please update the collection installation to the latest via the following command
- https://github.com/netscaler/ansible-collection-netscaleradc/blob/main/README.md#via-github-to-have-the-latest-updated-which-are-yet-to-be-released-in-ansible-galaxy

**Comment by QTjstahl** [comment]
Sure.  Here's the complete standalone playbook.  

`
---
- name: Configure NetScaler instances for TFTP
  hosts: netscaler
  gather_facts: false

  tasks:
  - name: Set Initial Facts
    set_fact:
      tftp1: "{{ groups['tftp'][0] }}"
      tftp2: "{{ groups['tftp'][1] }}"
      tftp_servicegroup: "{{ groups['tftp'][0] | regex_replace('...$', '') + '_tftp_69' }}"

      nios_provider:
        host: "{{ groups['nios'][0] }}"
        username: "{{ nios_user }}"
        password: "{{ nios_pass }}"

      netscaler_login_info: &netscaler_login_info
          nsip: "{{ inventory_hostname }}"
          nitro_user: "{{ nitro_user }}"
          nitro_pass: "{{ nitro_pass }}"
          validate_certs: no

  - name: Add TFTP1 server
    delegate_to: localhost
    netscaler.adc.server:
      <<: *netscaler_login_info
      state: present
      name: "{{ tftp1 }}"
      domain: "{{ tftp1 }}.testlab.com"
    
  - name: Add TFTP2 server
    delegate_to: localhost
    netscaler.adc.server:
      <<: *netscaler_login_info
      state: present
      name: "{{ tftp2 }}"
      domain: "{{ tftp2 }}.testlab.com"

  - name: Create TFTP Service group
    delegate_to: localhost
    netscaler.adc.servicegroup:
      <<: *netscaler_login_info
      state: present
      servicegroupname: "{{ tftp_servicegroup }}"
      servicetype: "TFTP"
  
  - name: Bind TFTP1 to Service group
    delegate_to: localhost
    netscaler.adc.servicegroup_servicegroupmember_binding:
      <<: *netscaler_login_info
      servicegroupname: "{{ tftp_servicegroup }}"
      servername: "{{ tftp1 }}"
      port: 69

  - name: Bind TFTP2 to Service group
    delegate_to: localhost
    netscaler.adc.servicegroup_servicegroupmember_binding:
      <<: *netscaler_login_info
      servicegroupname: "{{ tftp_servicegroup }}"
      servername: "{{ tftp2 }}"
      port: 69

  - name: Create TFTP Custom Monitor for Auto Deploy
    delegate_to: localhost
    netscaler.adc.lbmonitor:
      <<: *netscaler_login_info
      monitorname: vSphereAutoDeploy_TFTP_Monitor
      state: present
      type: USER
      interval: 5
      resptimeout: 2
      scriptname: "nstftp.pl"
      scriptargs: "file=tramp;content=#!gpxe"

  - name: Bind TFTP Monitor to Service Group
    delegate_to: localhost
    netscaler.adc.servicegroup_lbmonitor_binding:
      <<: *netscaler_login_info
      state: present
      monitor_name: vSphereAutoDeploy_TFTP_Monitor
      monstate: "ENABLED"
      port: 69
      servicegroupname: "{{ tftp_servicegroup }}"

  - name: Set FQDN of TFTP LBVIP
    set_fact:
      lbvip_fqdn: "{{ tftp_servicegroup }}.testlab.com"

  - name: Configure an IPv4 Host Record
    delegate_to: nios
    connection: local
    nios_host_record:
      name: "{{ lbvip_fqdn }}"
      ipv4addrs:
        - ipv4addr:
            "{{ lookup('nios_next_ip', '10.99.1.0/24', provider=nios_provider)[0] }}"
      state: present
      provider: "{{ nios_provider }}"

  - name: Fetch the LBVIP assigned IP address
    set_fact:
      host_record: "{{ lookup('nios', 'record:host', filter={'name': lbvip_fqdn}, provider=nios_provider) }}"

  - name: Create LBVIP for AutoDeploy TFTP and bind to Service Group
    delegate_to: localhost
    netscaler.adc.lbvserver:
      <<: *netscaler_login_info
      state: enabled

      name: "LBVIP_{{ lbvip_fqdn }}"
      servicetype: "TFTP"
      ipv46: "{{ host_record.ipv4addrs[0].ipv4addr }}"
      port: 69
      lbmethod: LEASTCONNECTION

      lbvserver_servicegroup_binding:
        binding_members:
          - name: "LBVIP_{{ lbvip_fqdn }}"
            servicename: "{{ tftp_servicegroup }}"
      
      save_config: true
`

Also, I attempted to update the collection as referenced, however it failed stating that the collection name wasn't correct. 
`
 git clone --single-branch https://github.com/netscaler/ansible-collection-netscaleradc.git /tmp/ansible-collection-netscaleradc && ansible-galaxy collection install /tmp/ansible-collection-netscaleradc --force
Cloning into '/tmp/ansible-collection-netscaleradc'...
remote: Enumerating objects: 18273, done.
remote: Counting objects: 100% (2022/2022), done.
remote: Compressing objects: 100% (1160/1160), done.
remote: Total 18273 (delta 1805), reused 1011 (delta 859), pack-reused 16251
Receiving objects: 100% (18273/18273), 58.26 MiB | 30.13 MiB/s, done.
Resolving deltas: 100% (15469/15469), done.
Starting galaxy collection install process
Process install dependency map
ERROR! Invalid collection name '/tmp/ansible-collection-netscaleradc', name must be in the format <namespace>.<collection>.
Please make sure namespace and collection name contains characters from [a-zA-Z0-9_] only.`

**Comment by sumanth-lingappa** [comment]
Thank you @QTjstahl for the standalone playbook. I could reproduce the issue. Please expect a fix in a couple of days.

**Comment by QTjstahl** [comment]
@sumanth-lingappa That'd be amazing.  Thanks so much for looking into this.  Great modules and I really appreciate your contributions here!

**Comment by sumanth-lingappa** [comment]
@QTjstahl, `port` is not a valid attribute for `servicegroup_lbmonitor_binding`. Due to NITRO documentation bug, the `netscaler.adc` collection was considering `port` as a valid option.

Now this fix makes sure `port` is not a valid attribute for the above binding.

Please remove `port` attribute from the `netscaler.adc.servicegroup_lbmonitor_binding` task.
